doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(default:MONGODB_URI:mongodb://localhost:27017)%'
            options: 
                ssl: true
                authSource: admin
                retryWrites: true
    default_database: '%env(default:MONGODB_DB:securehealth)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App