doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URI)%'
            options: 
                ssl: true
                authSource: admin
                retryWrites: true
                readPreference: primary
                writeConcern: 
                    w: majority
                    j: true
                serverSelectionTimeoutMS: 30000
                connectTimeoutMS: 30000
                socketTimeoutMS: 30000
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App