framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.cache_dir%/sessions'
        cookie_httponly: true
        cookie_lifetime: 86400
        gc_maxlifetime: 86400

    php_errors:
        log: true