framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.project_dir%/var/cache/sessions'
        cookie_httponly: true
        cookie_lifetime: 0
        gc_maxlifetime: 1440

    php_errors:
        log: true