security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    doctor@example.com:
                        password: '$2y$13$TkooOBqBQPtvya8qYqJL4.jI0rmgcuLTdXtz8bKzVF9KK8ouD1cuS'  # password is 'doctor'
                        roles: ['ROLE_DOCTOR']
                    nurse@example.com:
                        password: '$2y$13$WlhL0xPY9mMA.wJwadXaF.NiWPb4U7WgzGa.sKr.nTDs1epN6e87W'  # password is 'nurse'
                        roles: ['ROLE_NURSE']
                    receptionist@example.com:
                        password: '$2y$13$BbbmXCjLGXj7NrYaQdxlO.nN5kiNXlxAtxWLJagftoDL3w15.YOUu'  # password is 'receptionist'
                        roles: ['ROLE_RECEPTIONIST']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            custom_authenticators:
                - App\Security\SessionAuthenticator
            logout:
                path: app_logout
                target: app_login

    # Configure access control based on paths and roles
    access_control:
        # Documentation Access Control
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        # API Access Control
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/patients, roles: IS_AUTHENTICATED_FULLY }
        # Create, update, delete operations restricted to doctors
        - { path: ^/api/patients$, methods: [POST], roles: ROLE_DOCTOR }
        - { path: ^/api/patients/\d+$, methods: [PUT, DELETE], roles: ROLE_DOCTOR }
        # Read operations allowed for all authenticated healthcare staff
        - { path: ^/api/patients, methods: [GET], roles: [ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST] }

    role_hierarchy:
        # Doctor has all permissions
        ROLE_DOCTOR: [ROLE_NURSE, ROLE_RECEPTIONIST]
        # Nurse has more permissions than receptionist
        ROLE_NURSE: [ROLE_RECEPTIONIST]