security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            id: App\Security\SessionUserProvider
        document_user_provider:
            id: App\Security\DocumentUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        debug:
            pattern: ^/debug
            security: false
        public_api:
            pattern: ^/api/(health|patient-portal/register|patient-portal/health)
            security: false
        main:
            pattern: ^/
            lazy: false
            stateless: false
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JsonLoginAuthenticator
                - App\Security\SessionAuthenticator
            logout:
                path: /api/logout
                target: /login.html
            entry_point: App\Security\SessionAuthenticator

    # Configure access control based on paths and roles
    access_control:
        # Debug Access Control
        - { path: ^/debug, roles: PUBLIC_ACCESS }
        - { path: ^/api/debug, roles: PUBLIC_ACCESS }
        - { path: ^/api/test, roles: PUBLIC_ACCESS }
        # Documentation Access Control
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        # API Access Control
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }
        # Patient Portal API access control - specific routes first
        - { path: ^/api/patient-portal/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/patient-portal/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/patient-portal/appointments, roles: ROLE_PATIENT }
        - { path: ^/api/patient-portal, roles: ROLE_PATIENT }
        # Patient operations - specific patterns first (more specific to less specific)
        - { path: '^/api/patients/[a-f0-9]{24}$', methods: [GET, PUT, DELETE], roles: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST] }
        - { path: ^/api/patients$, methods: [POST], roles: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST] }
        - { path: ^/api/patients, methods: [GET], roles: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST] }
        # Admin API access control
        - { path: ^/api/admin, roles: [ROLE_ADMIN, ROLE_DOCTOR] }
        # Admin web interface access control
        - { path: ^/admin, roles: [ ROLE_ADMIN, ROLE_DOCTOR] }
        # Appointments API access control - allow healthcare staff
        - { path: ^/api/appointments, roles: [ROLE_RECEPTIONIST, ROLE_DOCTOR, ROLE_NURSE, ROLE_ADMIN] }
        # Audit logs API access control - allow doctors and admins
        - { path: ^/api/audit-logs, roles: [ROLE_DOCTOR, ROLE_ADMIN] }
        # Role-specific documentation API access control
        - { path: ^/api/role-documentation, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/role-features, roles: IS_AUTHENTICATED_FULLY }
        # Wizard API access control - all authenticated users
        - { path: ^/api/wizard, roles: IS_AUTHENTICATED_FULLY }
        # Wizard web interface access control
        - { path: ^/wizard.html, roles: IS_AUTHENTICATED_FULLY }
        # Medical Knowledge API access control
        - { path: ^/api/medical-knowledge/search, roles: [ROLE_DOCTOR, ROLE_ADMIN] }
        - { path: ^/api/medical-knowledge/clinical-decision-support, roles: ROLE_DOCTOR }
        - { path: ^/api/medical-knowledge/drug-interactions, roles: [ROLE_DOCTOR, ROLE_NURSE, ROLE_ADMIN] }
        - { path: ^/api/medical-knowledge/treatment-guidelines, roles: ROLE_DOCTOR }
        - { path: ^/api/medical-knowledge/diagnostic-criteria, roles: ROLE_DOCTOR }
        - { path: ^/api/medical-knowledge/stats, roles: [ROLE_DOCTOR, ROLE_ADMIN] }
        - { path: ^/api/medical-knowledge, roles: [ROLE_DOCTOR, ROLE_NURSE, ROLE_ADMIN] }
        
        # Chatbot API access control
        - { path: ^/api/chatbot, roles: [ROLE_DOCTOR, ROLE_NURSE, ROLE_ADMIN] }

    role_hierarchy:
        # Admin has all permissions including doctor permissions
        ROLE_ADMIN: [ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST]
        # Doctor has nurse and receptionist permissions
        ROLE_DOCTOR: [ROLE_NURSE, ROLE_RECEPTIONIST]
        # Nurse has more permissions than receptionist
        ROLE_NURSE: [ROLE_RECEPTIONIST]
        # Patients have their own separate role hierarchy
        ROLE_PATIENT: [ROLE_USER]