[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "echo 'Build phase complete'",
  "php bin/console cache:clear --env=prod --no-debug"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
