[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public public/router.php"
