controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Import specific route files
docs_static_routes:
    resource: ../src/Controller/DocsStaticController.php
    type: attribute

main_routes:
    resource: ../src/Controller/MainController.php
    type: attribute

# Security routes are handled by SecurityController.php with attributes

app_health:
    path: /api/health
    controller: App\Controller\HealthCheckController::index
    methods: GET