parameters:
    mongodb_url: '%env(default:mongodb://localhost:27017:MONGODB_URI)%'
    mongodb_db: '%env(default:securehealth:MONGODB_DB)%'
    mongodb_key_vault_namespace: '%env(default:encryption.__keyVault:MONGODB_KEY_VAULT_NAMESPACE)%'
    mongodb_encryption_key_path: '%env(default:/app/docker/encryption.key:MONGODB_ENCRYPTION_KEY_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    # Alias MongoDB\Client to the doctrine_mongodb.odm.default_connection service
    MongoDB\Client:
        alias: doctrine_mongodb.odm.default_connection
        public: false