parameters:
    mongodb_url: '%env(default:MONGODB_URI:mongodb://localhost:27017)%'
    mongodb_db: '%env(default:MONGODB_DB:securehealth)%'
    mongodb_key_vault_namespace: '%env(default:MONGODB_KEY_VAULT_NAMESPACE:encryption.__keyVault)%'
    mongodb_encryption_key_path: '%env(default:MONGODB_ENCRYPTION_KEY_PATH:/app/docker/encryption.key)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    # Alias MongoDB\Client to the doctrine_mongodb.odm.default_connection service
    MongoDB\Client:
        alias: doctrine_mongodb.odm.default_connection
        public: false