parameters:
    mongodb_url: '%env(resolve:MONGODB_URI)%'
    mongodb_db: '%env(resolve:MONGODB_DB)%'
    mongodb_key_vault_namespace: '%env(resolve:MONGODB_KEY_VAULT_NAMESPACE)%'
    mongodb_encryption_key_path: '%env(resolve:MONGODB_ENCRYPTION_KEY_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    # Use encrypted MongoDB client for HIPAA compliance
    MongoDB\Client:
        factory: ['@App\Factory\MongoDBConnectionFactory', 'createEncryptedClient']
        arguments: ['%env(resolve:MONGODB_URI)%']
        public: false

    # Medical Knowledge Services
    App\Service\EmbeddingService:
        arguments:
            $openaiApiKey: '%env(OPENAI_API_KEY)%'
            $openaiApiUrl: '%env(OPENAI_API_URL)%'

    App\Service\MedicalKnowledgeService:
        arguments:
            $repository: '@App\Repository\MedicalKnowledgeRepository'
            $embeddingService: '@App\Service\EmbeddingService'
            $logger: '@logger'

    App\Service\VectorSearchService:
        arguments:
            $knowledgeRepository: '@App\Repository\MedicalKnowledgeRepository'
            $embeddingService: '@App\Service\EmbeddingService'
            $logger: '@logger'

    App\Repository\MedicalKnowledgeRepository:
        arguments:
            $dm: '@doctrine_mongodb.odm.default_document_manager'
            $encryptionService: '@App\Service\MongoDBEncryptionService'

    # RAG Knowledge Base Command
    App\Command\IndexKnowledgeBaseCommand:
        arguments:
            $mongoClient: '@MongoDB\Client'
            $projectDir: '%kernel.project_dir%'
            $openaiApiKey: '%env(OPENAI_API_KEY)%'